name: PR Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint_output=$(pylint projects --exit-zero)
          echo "$pylint_output"
          score=$(echo "$pylint_output" | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
          echo "Pylint score: $score"
          # Convert score to integer for comparison by multiplying by 10 (to avoid float issues)
          score_int=$(echo "$score * 10 / 1" | bc)
          if [ "$score_int" -lt 80 ]; then
            echo "Pylint score is below 8.0, failing the job."
            exit 1
          fi

      - name: Run tests
        run: |
          python manage.py test
